routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');
Route::resource('/','ContractsController');
Route::resource('contracts','ContractsController');
Route::get('tasks/create/{contract_id?}', 'TasksController@create');
Route::resource('tasks', 'TasksController');
Route::resource('stock', 'StockController');
Route::resource('definedtasks', 'DefinedTasksController');
Route::resource('subdefinedtasks', 'SubdefinedTasksController');
Route::resource('employees', 'EmployeesController');
Route::resource('clients', 'ClientsController');
Route::resource('contracts_statuses', 'ContractsStatusController');
Route::resource('contracts_types', 'ContractsTypesController');
Route::resource('upload', 'DownloadFilesController');
Route::resource('statistics', 'StatisticsController');
Route::resource('statisticsclient', 'StatisticsClientController');
Route::resource('diary', 'DiaryController');
Route::resource('cash', 'CashController');
Route::get('/contracts/getPDF/{id}','ContractsController@generatePDF');
Route::resource('deadline', 'ContractsDeadlineesController');
Route::get('reminders/all', 'ReminderController@all');
Route::resource('reminders', 'ReminderController');
Route::resource('taskstatistics', 'TaskStatisticsController');
Route::resource('sendstock', 'SendStockController');
Route::resource('contractors', 'ContractorController');
Route::resource('status_invoice', 'StatusInvoiceController');
Route::resource('invoice_payment', 'InvoicePaymentMethodController');
Route::resource('invoice', 'InvoiceController');
Route::resource('invoice_detail', 'InvoiceDetailController');
Route::get('/invoice/getPDF/{id}','InvoiceController@generatePDF');
Route::get('/invoice/dodaci-list/{id}','InvoiceController@generatePDFdodaci');
// Route::get('/invoice/print/{id}','InvoiceController@print');
Route::resource('messages', 'MessageController');
Route::resource('price_offers', 'PriceOfferController');
Route::get('/price_offers/getPDF/{id}','PriceOfferController@generatePDF');
Route::resource('users', 'UserController');
Route::resource('statisticsinvoice', 'StatisticsInvoicesController');
Route::resource('priceoffer_detail', 'PriceOfferDetailController');
Route::resource('client_export', 'ClientExportController');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'id',
        'nazov_firmy',
        'kontaktna_osoba',
        'email',
        'telefon',
        'mobil',
        'ico',
        'dic',
        'icdph',
        'fa_adresa',
        'fa_mesto',
        'fa_psc',
        'fa_krajina',
        'pdfheslo',

    ];
    public function user(){
        return $this->belongsToMany('App\User');
    }

    public function contract(){
        return $this->belongsTo('App\Contract');

    }
}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Log;
use Carbon\Carbon;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if((Auth::check())&&(((Auth::user()->mod_1)==1)||((Auth::user()->mod_10)==1))){
        $clients= Client::all();
        return view('clients.index',['clients'=>$clients]);
        }
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::check()){
        return view('clients.create');
        }
        return back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if((Auth::check())&&(((Auth::user()->mod_1)==1)||((Auth::user()->mod_10)==1))){
            $client = Client::create([
                'nazov_firmy' => $request->input('nazov_firmy'),
                'kontaktna_osoba' => $request->input('kontaktna_osoba'),
                'ico' => $request->input('ico'),
                'dic' => $request->input('dic'),
                'icdph' => $request->input('icdph'),
                'fa_adresa' => $request->input('fa_adresa'),
                'fa_mesto' => $request->input('fa_mesto'),
                'fa_psc' => $request->input('fa_psc'),
                'fa_krajina' => $request->input('fa_krajina'),
                'telefon' => $request->input('telefon'),
                'mobil' => $request->input('mobil'),
                'email' => $request->input('email'),
                'pdfheslo' => $request->input('pdfheslo'),

            ]);
            if($client){

                $ip_adresa = $request->getClientIp();
                $cas = Carbon::now()->toDateTimeString();
                Log::channel('client')->info('Používateľ : '.Auth::user()->name.' ID: '.Auth::user()->id.' vytvoril klienta s ID: '.$client->id.' Názov firmy: '.$client->nazov_firmy.' Kontaktná osoba: '.$client->kontaktna_osoba.' IČO: '.$client->ico.' DIČ: '.$client->dic.' IČDPH: '.$client->icdph.' Fakturačná adresa: '.$client->fa_adresa.' Mesto: '.$client->fa_mesto.' PSČ: '.$client->fa_psc.' Krajina: '.$client->fa_krajina.' Telefón: '.$client->telefon.' Mobil: '.$client->mobil.' E-MAIL: '.$client->email.' z IP: '.$ip_adresa.' v čase: '.$cas);

                return redirect()->route('clients.index')->with('success_message', 'Klient bol úspešne vytvorený');
            }
        }

        return back()->withInput()->with('danger_message', 'Vytvorenie klienta skončilo chybou.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if((Auth::check())&&(((Auth::user()->mod_1)==1)||((Auth::user()->mod_10)==1))){
        $findclient = Client::find($id);
        return view('clients.edit',['client'=>$findclient]);
        }
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        if((Auth::check())&&(((Auth::user()->mod_1)==1)||((Auth::user()->mod_10)==1))){
        $updated = $client->update([
            'nazov_firmy' => $request->input('nazov_firmy'),
            'kontaktna_osoba' => $request->input('kontaktna_osoba'),
            'ico' => $request->input('ico'),
            'dic' => $request->input('dic'),
            'icdph' => $request->input('icdph'),
            'fa_adresa' => $request->input('fa_adresa'),
            'fa_mesto' => $request->input('fa_mesto'),
            'fa_psc' => $request->input('fa_psc'),
            'fa_krajina' => $request->input('fa_krajina'),
            'telefon' => $request->input('telefon'),
            'mobil' => $request->input('mobil'),
            'email' => $request->input('email'),
            'pdfheslo' => $request->input('pdfheslo')
        ]);
        if (! $updated){
            return back()->withInput();
        }
            $ip_adresa = $request->getClientIp();
            $cas = Carbon::now()->toDateTimeString();
            Log::channel('client')->info('Používateľ : '.Auth::user()->name.' ID: '.Auth::user()->id.' aktualizoval klienta s ID: '.$client->id.' Názov firmy: '.$client->nazov_firmy.' Kontaktná osoba: '.$client->kontaktna_osoba.' IČO: '.$client->ico.' DIČ: '.$client->dic.' IČDPH: '.$client->icdph.' Fakturačná adresa: '.$client->fa_adresa.' Mesto: '.$client->fa_mesto.' PSČ: '.$client->fa_psc.' Krajina: '.$client->fa_krajina.' Telefón: '.$client->telefon.' Mobil: '.$client->mobil.' E-MAIL: '.$client->email.' z IP: '.$ip_adresa.' v čase: '.$cas);
        return redirect()->route('clients.index')
            ->with('success_message','Klient bol úspešne aktualizovaý.');
        }
        return back();


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy()
    {

    }
}

resources/views/clients/create.blade.php
@extends('admin_template')

@section('content')
            <div class="row">

                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Pridať klienta</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form  method="post" action="{{ route('clients.store') }}" role="form">
                            {{ csrf_field() }}
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Obchodné meno:</label>
                                    <input name="nazov_firmy" type="text" required class="form-control" id="exampleInputEmail1" placeholder="Zadajte obchodné meno">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Kontaktná osoba:</label>
                                    <input name="kontaktna_osoba" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte kontaktnú osobu">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">IČO:</label>
                                    <input name="ico" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte ičo">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">DIČ:</label>
                                    <input name="dic" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte dič">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">IČ DPH:</label>
                                    <input name="icdph" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte IČ DPH">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Adresa:</label>
                                    <input name="fa_adresa" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte adresu">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Mesto:</label>
                                    <input name="fa_mesto" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte mesto">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">PSČ:</label>
                                    <input name="fa_psc" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte psč">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Krajina</label>
                                    <input name="fa_krajina" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte krajinu">
                                </div>

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Telefón:</label>
                                    <input name="telefon" type="tel" class="form-control" id="exampleInputEmail1" placeholder="Zadajte telefón">
                                </div>


                                <div class="form-group">
                                    <label for="exampleInputEmail1">Mobil:</label>
                                    <input name="mobil" type="tel" class="form-control" id="exampleInputEmail1" placeholder="Zadajte mobil">
                                </div>


                                <div class="form-group">
                                    <label for="exampleInputEmail1">E-MAIL:</label>
                                    <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Zadajte email">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Heslo pre pdf súbory</label>
                                    <input name="pdfheslo" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte heslo pre pdf subory">
                                </div>
                            </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.tab-pane -->
            </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>


@endsection

resources/views/clients/edit.blade.php
@extends('admin_template')

@section('content')
            <div class="row">

                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Upraviť klienta</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form  method="post" action="{{route('clients.update',[$client->id])}}" role="form">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Obchodné meno:</label>
                                    <input name="nazov_firmy" value="{{$client->nazov_firmy}}" type="text" required class="form-control" id="exampleInputEmail1" placeholder="Zadajte obchodné meno">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Kontaktná osoba:</label>
                                    <input name="kontaktna_osoba" value="{{$client->kontaktna_osoba}}" type="text" class="form-control" id="exampleInputEmail1" placeholder="Zadajte kontaktnú osobu">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">IČO:</label>
                                    <input name="ico" type="text" value="{{$client->ico}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte ičo">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">DIČ:</label>
                                    <input name="dic" type="text" value="{{$client->dic}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte dič">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">IČ DPH:</label>
                                    <input name="icdph" type="text" value="{{$client->icdph}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte IČ DPH">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Adresa:</label>
                                    <input name="fa_adresa" type="text" value="{{$client->fa_adresa}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte adresu">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Mesto:</label>
                                    <input name="fa_mesto" type="text" value="{{$client->fa_mesto}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte mesto">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">PSČ:</label>
                                    <input name="fa_psc" type="text" value="{{$client->fa_psc}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte psč">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Krajina</label>
                                    <input name="fa_krajina" type="text" value="{{$client->fa_krajina}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte krajinu">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Telefón:</label>
                                    <input name="telefon" type="tel" value="{{$client->telefon}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte telefón">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Mobil:</label>
                                    <input name="mobil" type="tel" value="{{$client->mobil}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte mobil">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">E-MAIL:</label>
                                    <input name="email" type="email" value="{{$client->email}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte email">
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Heslo pre pdf súbory</label>
                                    <input name="pdfheslo" type="text" value="{{$client->pdfheslo}}" class="form-control" id="exampleInputEmail1" placeholder="Zadajte heslo pre pdf subory">
                                </div>
                             </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.tab-pane -->
            </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>



@endsection

resources/views/clients/index.blade.php
@extends('admin_template')

@section('content')
    <div class='row'>
        <div class='col-md-12'>
            <a href="/clients/create" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Pridať nového klienta</a>
            <!-- Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Zoznam klientov</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>

                <div class="box-body">

                    <div class="box">

                        <!-- /.box-header -->
                        <div class="table-responsive ">

                            <table id="example1" class="table table-bordered table-striped">
                                <tr>
                                    <th>Poradové číslo:</th>
                                    <th>Obchodné meno:</th>
                                    <th>Kontaktná osoba:</th>
                                    <th>IČO:</th>
                                    <th>DIČ:</th>
                                    <th>IČDPH:</th>
                                    <th>Adresa:</th>
                                    <th>Mesto:</th>
                                    <th>PSČ:</th>
                                    <th>Krajina</th>
                                    <th>Telefón:</th>
                                    <th>Mobil:</th>
                                    <th>E-MAIL:</th>
                                    <th>Editácia</th>



                                </tr>
                                <div style="display: none;">
                                    {{ $i=1 }}
                                </div>

                                @foreach ($clients as  $client)
                                    <tr>
                                        <td>{{ $i++ }}</td>
                                        <td>{{ $client->nazov_firmy}}</td>
                                        <td>{{ $client->kontaktna_osoba}}</td>
                                        <td>{{ $client->ico}}</td>
                                        <td>{{ $client->dic}}</td>
                                        <td>{{ $client->icdph}}</td>
                                        <td>{{ $client->fa_adresa}}</td>
                                        <td>{{ $client->fa_mesto}}</td>
                                        <td>{{ $client->fa_psc}}</td>
                                        <td>{{ $client->fa_krajina}}</td>
                                        <td>{{ $client->telefon}}</td>
                                        <td>{{ $client->mobil}}</td>
                                        <td>{{ $client->email}}</td>
                                        <td><a href="/clients/{{ $client->id }}/edit">Editovať</a></td>
                                    </tr>


                                @endforeach

                            </table>


                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div><!-- /.box-body -->

            </div><!-- /.box -->
        </div><!-- /.col -->



    </div><!-- /.row -->

@endsection