routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');
Route::resource('/','ContractsController');
Route::resource('contracts','ContractsController');
Route::get('tasks/create/{contract_id?}', 'TasksController@create');
Route::resource('tasks', 'TasksController');
Route::resource('stock', 'StockController');
Route::resource('definedtasks', 'DefinedTasksController');
Route::resource('subdefinedtasks', 'SubdefinedTasksController');
Route::resource('employees', 'EmployeesController');
Route::resource('clients', 'ClientsController');
Route::resource('contracts_statuses', 'ContractsStatusController');
Route::resource('contracts_types', 'ContractsTypesController');
Route::resource('upload', 'DownloadFilesController');
Route::resource('statistics', 'StatisticsController');
Route::resource('statisticsclient', 'StatisticsClientController');
Route::resource('diary', 'DiaryController');
Route::resource('cash', 'CashController');
Route::get('/contracts/getPDF/{id}','ContractsController@generatePDF');
Route::resource('deadline', 'ContractsDeadlineesController');
Route::get('reminders/all', 'ReminderController@all');
Route::resource('reminders', 'ReminderController');
Route::resource('taskstatistics', 'TaskStatisticsController');
Route::resource('sendstock', 'SendStockController');
Route::resource('contractors', 'ContractorController');
Route::resource('status_invoice', 'StatusInvoiceController');
Route::resource('invoice_payment', 'InvoicePaymentMethodController');
Route::resource('invoice', 'InvoiceController');
Route::resource('invoice_detail', 'InvoiceDetailController');
Route::get('/invoice/getPDF/{id}','InvoiceController@generatePDF');
Route::get('/invoice/dodaci-list/{id}','InvoiceController@generatePDFdodaci');
// Route::get('/invoice/print/{id}','InvoiceController@print');
Route::resource('messages', 'MessageController');
Route::resource('price_offers', 'PriceOfferController');
Route::get('/price_offers/getPDF/{id}','PriceOfferController@generatePDF');
Route::resource('users', 'UserController');
Route::resource('statisticsinvoice', 'StatisticsInvoicesController');
Route::resource('priceoffer_detail', 'PriceOfferDetailController');
Route::resource('client_export', 'ClientExportController');

app/SubdefinedTask.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubdefinedTask extends Model
{
    protected $fillable = [
        'id',
        'nazov',
        'nadradena_kat_id',
        'cena_material_kg',

    ];
    public function user(){
        return $this->belongsToMany('App\User');
    }
    public function defined_task(){
        return $this->hasMany('App\DefinedTask');

    }
    public function subdefined_task()
    {
        return $this->belongsTo('App\Contract');
    }

}

app/Http/Controllers/SubdefinedTasksController.php
<?php

namespace App\Http\Controllers;

use App\SubdefinedTask;
use App\DefinedTask;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Log;

class SubdefinedTasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        $subdefinedTasks= SubdefinedTask::all();
        $definedtasks=DefinedTask::all();
        return view('subdefined_tasks.index',['definedTasks'=>$definedtasks,'subdefinedTasks'=>$subdefinedTasks]);
        }
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        $definedtask=DefinedTask::all();
        return view('subdefined_tasks.create',['definedtask'=>$definedtask]);
        }
        return back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $definedtask=DefinedTask::all();
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
            $subdefinedtask = SubdefinedTask::create([
                'nazov' => $request->input('nazov'),
                'nadradena_kat_id' => $request->input('nadradena_kat_id'),
                'cena_material_kg' => $request->input('cena_material_kg')

            ]);
            if($subdefinedtask){
                $ip_adresa = $request->getClientIp();
                $cas = Carbon::now()->toDateTimeString();
                Log::channel('subdefinedtask')->info('Použivateľ : '.Auth::user()->name.' ID: '.Auth::user()->id.' vytvoril podkategoriu s ID: '.$subdefinedtask->id.' Nazov = '.$subdefinedtask->nazov.' Nadradena kat id = :'.$subdefinedtask->nadradena_kat_id.' Cena material kg = '.$subdefinedtask->cena_material_kg.' z IP: '.$ip_adresa.' v čase: '.$cas);
                return redirect()->route('subdefinedtasks.index');
            }
        }

        return back()->withInput()->with('errors', 'Error creating new company');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SubdefinedTask  $subdefinedTask
     * @return \Illuminate\Http\Response
     */
    public function show(SubdefinedTask $subdefinedTask)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SubdefinedTask  $subdefinedTask
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        $findsubdefinedTask= SubdefinedTask::find($id);
        $definedtask=DefinedTask::all();
        return view('subdefined_tasks.edit',['subdefinedTask'=>$findsubdefinedTask,'definedTask'=>$definedtask]);
        }
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubdefinedTask  $subdefinedTask
     * @return \Illuminate\Http\Response
     */
  /*  public function update(Request $request, SubdefinedTask $subdefinedTask)
    {
        $updated = $subdefinedTask->update([
            'nazov' => $request->input('nazov'),
            'nadradena_kat_id' => $request->input('nadradena_kat_id')
        ]);

        if (! $updated){

            return back()->withInput();
        }
        return redirect()->route('subdefinedtasks.index')
            ->with('success','Defined task update successfully');

    } */
    public function update($id, Request $request)
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        try {
            $task = SubdefinedTask::findOrFail($id);

            $this->validate($request, [
                'nazov' => 'required',
                'nadradena_kat_id' => 'required'
            ]);

            $input = $request->all();

            $task->fill($input)->save();

            $ip_adresa = $request->getClientIp();
            $cas = Carbon::now()->toDateTimeString();
            Log::channel('subdefinedtask')->info('Použivateľ : '.Auth::user()->name.' ID: '.Auth::user()->id.' aktualizoval podkategoriu s ID: '.$task->id.' na Nazov = '.$task->nazov.' Nadradena kat id = :'.$task->nadradena_kat_id.' Cena material kg = '.$task->cena_material_kg.' z IP: '.$ip_adresa.' v čase: '.$cas);

            return redirect()->route('subdefinedtasks.index');

        }
        catch (\Exception $e) {
            return $e->getMessage();
        }
        }
        return back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\SubdefinedTask  $subdefinedTask
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        try {
            $findsubdefinedTask = SubdefinedTask::find($id);

            $findsubdefinedTask ->delete();
            return redirect()->route('subdefinedtasks.index');
        }
        catch (\Exception $e) {
            return $e->getMessage();
        }
        }
        return back();
    }
}

resources/views/subdefined_tasks/create.blade.php
@extends('admin_template')

@section('content')
            <div class="row">

                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Pridať podkategóriu</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form  method="post" action="{{ route('subdefinedtasks.store') }}" role="form">
                            {{ csrf_field() }}
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Názov podkategórie</label>
                                    <input name="nazov" type="text" required class="form-control" id="exampleInputEmail1" placeholder="Zadajte názov podkategórie">
                                </div>
                                <div class="form-group">
                                    <label>Nadradená kategória:</label>
                                    <select name="nadradena_kat_id" class="form-control">
                                        @foreach($definedtask as $definedtask2)
                                            <option value="{{$definedtask2->id}}">{{$definedtask2->nazov}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputCenaMaterialu">Cena materiálu za 1 kg</label>
                                    <input name="cena_material_kg" type="number" step="0.01" min="0" required class="form-control" id="exampleInputCenaMaterialu" placeholder="Zadajte cenu materiálu za 1kg">
                                </div>

                             </div>

                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.tab-pane -->
            </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>


@endsection

resources/views/subdefined_tasks/edit.blade.php
@extends('admin_template')

@section('content')
            <div class="row">

                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Upraviť podkategóriu</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form  method="post" action="{{route('subdefinedtasks.update',[$subdefinedTask->id])}}" role="form">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Názov podkategórie</label>
                                    <input name="nazov" value="{{$subdefinedTask->nazov}}" type="text" required class="form-control" id="exampleInputEmail1" placeholder="Zadajte názov podkategórie">
                                </div>
                                <div class="form-group">
                                    <label>Nadradená kategória:</label>
                                    <select name="nadradena_kat_id" class="form-control">
                                        @foreach ($definedTask as $definedTask2)
                                            @if($definedTask2->id == $subdefinedTask->nadradena_kat_id)
                                                <option value="{{$definedTask2->id}}" selected>{{$definedTask2->nazov}}</option>
                                            @else
                                                <option value="{{$definedTask2->id}}" >{{$definedTask2->nazov}}</option>
                                            @endif
                                        @endforeach

                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputCenaMaterialu">Cena materiálu za 1 kg</label>
                                    <input name="cena_material_kg" value="{{$subdefinedTask->cena_material_kg}}" type="number" step="0.01" min="0" required class="form-control" id="exampleInputCenaMaterialu" placeholder="Zadajte cenu materiálu za 1kg">
                                </div>

                             </div>

                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.tab-pane -->
            </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>


@endsection

resources/views/subdefined_tasks/index.blade.php
@extends('admin_template')

@section('content')
    <div class='row'>
        <div class='col-md-12'>
            <a href="/subdefinedtasks/create" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Pridať podkategóriu</a>
            <!-- Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Zoznam podkategórii</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>

                <div class="box-body">
                    <div class="box">
                        <!-- /.box-header -->
                        <div class="box-body">

                            <table id="example1" class="table table-bordered table-striped">
                                <tr>
                                    <th>Poradové číslo</th>
                                    <th>Názov podkategórie</th>
                                    <th>Názov nadradenej kategórie</th>
                                    <th>Cena materiálu za 1 kg</th>
                                    <th>Editácia</th>



                                </tr>
                                <div style="display: none;">
                                    {{ $i=1 }}
                                </div>

                                @foreach ($subdefinedTasks as $subdefinedTask)
                                    <tr>
                                        <td>{{ $i++ }}</td>
                                        <td>{{ $subdefinedTask->nazov }}</td>
                                        <td>
                                            @foreach($definedTasks as $definedTask)
                                                @if($subdefinedTask->nadradena_kat_id==$definedTask->id)
                                                    {{$definedTask->nazov}}
                                                @endif
                                            @endforeach
                                        </td>
                                        <td>{{ $subdefinedTask->cena_material_kg }} €</td>
                                        <td><a href="/subdefinedtasks/{{ $subdefinedTask->id }}/edit">Editovať</a></td>

                                    </tr>
                                @endforeach

                            </table>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div><!-- /.box-body -->

            </div><!-- /.box -->
        </div><!-- /.col -->



    </div><!-- /.row -->

@endsection