routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');
Route::resource('/','ContractsController');
Route::resource('contracts','ContractsController');
Route::get('tasks/create/{contract_id?}', 'TasksController@create');
Route::resource('tasks', 'TasksController');
Route::resource('stock', 'StockController');
Route::resource('definedtasks', 'DefinedTasksController');
Route::resource('subdefinedtasks', 'SubdefinedTasksController');
Route::resource('employees', 'EmployeesController');
Route::resource('clients', 'ClientsController');
Route::resource('contracts_statuses', 'ContractsStatusController');
Route::resource('contracts_types', 'ContractsTypesController');
Route::resource('upload', 'DownloadFilesController');
Route::resource('statistics', 'StatisticsController');
Route::resource('statisticsclient', 'StatisticsClientController');
Route::resource('diary', 'DiaryController');
Route::resource('cash', 'CashController');
Route::get('/contracts/getPDF/{id}','ContractsController@generatePDF');
Route::resource('deadline', 'ContractsDeadlineesController');
Route::get('reminders/all', 'ReminderController@all');
Route::resource('reminders', 'ReminderController');
Route::resource('taskstatistics', 'TaskStatisticsController');
Route::resource('sendstock', 'SendStockController');
Route::resource('contractors', 'ContractorController');
Route::resource('status_invoice', 'StatusInvoiceController');
Route::resource('invoice_payment', 'InvoicePaymentMethodController');
Route::resource('invoice', 'InvoiceController');
Route::resource('invoice_detail', 'InvoiceDetailController');
Route::get('/invoice/getPDF/{id}','InvoiceController@generatePDF');
Route::get('/invoice/dodaci-list/{id}','InvoiceController@generatePDFdodaci');
// Route::get('/invoice/print/{id}','InvoiceController@print');
Route::resource('messages', 'MessageController');
Route::resource('price_offers', 'PriceOfferController');
Route::get('/price_offers/getPDF/{id}','PriceOfferController@generatePDF');
Route::resource('users', 'UserController');
Route::resource('statisticsinvoice', 'StatisticsInvoicesController');
Route::resource('priceoffer_detail', 'PriceOfferDetailController');
Route::resource('client_export', 'ClientExportController');

app/Reminder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reminder extends Model
{
    protected $fillable = [
        'id',
        'pripomienka',
        'datum',
        'opakovanie_num',
        'opakovanie_val',
        'pripomenutie_num',
        'pripomenutie_val',
        'stav',
        'user_id',
    ];
}

app/Http/Controllers/ReminderController.php
<?php

namespace App\Http\Controllers;

use App\Reminder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use View;
use Log;



class ReminderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        if((Auth::check())&&((Auth::user()->mod_7)==1)){
            $today = Carbon::now()->toDateString();
            $opakujuce_pripomienky=null;
            $neopakujuce_pripomienky=null;


            // Neopakujuce sa pripomienky
            $reminders = Reminder::where('stav', '1')->where('opakovanie_val','=','0')
                ->whereDate('datum', '>=', $today )->get();

            foreach ($reminders as $reminder) {
                $pripomienka_val = $reminder->pripomenutie_val;
                $pripomienka_num = $reminder->pripomenutie_num;
                //PRIPOMIENKA 1: dni; 2: tyzdne; 3:mesiace
                switch ($pripomienka_val) {
                    case 1:
                        $pripomienka_dni = $pripomienka_num;
                        break;
                    case 2:
                        $pripomienka_dni = $pripomienka_num * 7;
                        break;
                    case 3:
                        $pripomienka_dni = $pripomienka_num * 30;
                        break;
                }

              //  $date =date("Y-m-d", strtotime("$reminder->datum - $pripomienka_dni day"));
                $date_start= Carbon::parse($reminder->datum);
                $date = $date_start->subDays($pripomienka_dni);
                $datum = $reminder->datum;


                if ($date <= $today) {
                    //$neopakujuce_pripomienky[] = $reminder;
                    $neopakujuce_pripomienky[] = ['id'=>$reminder->id,'pripomienka'=>$reminder->pripomienka,'datum'=>$datum,'datumod'=>$date,'opakovanie_val'=>$reminder->opakovanie_val,'opakovanie_num'=>$reminder->opakovanie_num,'pripomenutie_num'=>$reminder->pripomenutie_num,'pripomenutie_val'=>$reminder->pripomenutie_val,'stav'=>$reminder->stav,'created_at'=>$reminder->created_at];

                }
            }
            // Koniec neopakujucich pripomienok
            // Začiatok opakovacích
            $reminders_opakujuce = Reminder::where('stav', '1')->where('opakovanie_val','!=','0')->get();

            foreach ($reminders_opakujuce as $reminder_opak)
            {
                $opkaovanie_val = $reminder_opak->opakovanie_val;
                $opakovanie_num = $reminder_opak->opakovanie_num;

                $pripomienka_val = $reminder_opak->pripomenutie_val;
                $pripomienka_num = $reminder_opak->pripomenutie_num;


                $start= Carbon::parse($reminder_opak->datum);
                $datenew = Carbon::parse($reminder_opak->datum);
                $end = Carbon::now()->toDateString();

                //OPAKOVANIE 1: dni; 2: tyzdne; 3: mesiace; 4: roky
                // https://carbon.nesbot.com/docs/
                switch ($opkaovanie_val) {
                    case 1: // Pridať dni
                        while($start < $end){

                            $start->addDays($opakovanie_num);
                            $datenew->addDays($opakovanie_num);
                        }

                        break;
                    case 2: // Pridať týždne

                        while($start < $end){

                            $start->addWeeks($opakovanie_num);
                            $datenew->addWeeks($opakovanie_num);
                        }
                        break;
                    case 3: // Pridať mesiace
                         while($start < $end){

                            $start->addMonths($opakovanie_num);
                            $datenew->addMonths($opakovanie_num);
                        }

                        break;
                    case 4: // Pridať roky
                        while($start < $end){

                            $start->addYears($opakovanie_num);
                            $datenew->addYears($opakovanie_num);
                            }
                        break;
                }

                // Pripomienka switch
                switch ($pripomienka_val) {
                    case 1:
                       $pripomienka_dni = $pripomienka_num;

                        break;
                    case 2:
                      $pripomienka_dni = $pripomienka_num * 7;

                        break;
                    case 3:
                       $pripomienka_dni = $pripomienka_num * 30;
                        break;
                                         }

                        $date = $start->subDays($pripomienka_dni);
                        $datum = $reminder_opak->datum;

                if ($date <= $today) {
                    $opakujuce_pripomienky[] = ['id'=>$reminder_opak->id,'pripomienka'=>$reminder_opak->pripomienka,'datum'=>$datum,'datumod'=>$date,'datumnew' => $datenew,'opakovanie_val'=>$reminder_opak->opakovanie_val,'opakovanie_num'=>$reminder_opak->opakovanie_num,'pripomenutie_num'=>$reminder_opak->pripomenutie_num,'pripomenutie_val'=>$reminder_opak->pripomenutie_val,'stav'=>$reminder_opak->stav,'created_at'=>$reminder_opak->created_at];
               }

            }
            // Koniec opakovacích pripomienok

            return view('reminders.index',['reminders'=>$neopakujuce_pripomienky, 'reminders_rep'=>$opakujuce_pripomienky]);
        }
        return back();
    }

    public function all()
    {
        if((Auth::check())&&((Auth::user()->mod_7)==1)){
            $reminders = Reminder::orderBy('id', 'DESC')->paginate(100);
            return view('reminders.all',['reminders'=>$reminders]);
        }
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::check()){
            return view('reminders.create');
        }
        return back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if((Auth::check())&&((Auth::user()->mod_7)==1)){
            $reminder = Reminder::create([
                'pripomienka' => $request->input('pripomienka'),
                'datum' => $request->input('terminpripomienky'),
                'opakovanie_val' => $request->input('opakovanie_val'),
                'opakovanie_num' => $request->input('opakovanie_num'),
                'pripomenutie_num' => $request->input('upozornenie_num'),
                'pripomenutie_val' => $request->input('upozornenie_val'),
                'stav' => $request->input('stavpripomienky'),
                'user_id' => Auth::id()

            ]);
            if($reminder){
                $ip_adresa = $request->getClientIp();
                $cas = Carbon::now()->toDateTimeString();
                Log::channel('reminders')->info('Použivateľ : '.Auth::user()->name.' ID: '.Auth::user()->id.' vytvoril pripomienku s ID: '.$reminder->id.' Pripomienka: '.$reminder->pripomienka.' Dátum pripomienky: '.$reminder->datum.' Opakovanie val: '.$reminder->opakovanie_val.' Opakovanie num: '.$reminder->opakovanie_num.' Pripomenutie num: '.$reminder->pripomenutie_num.' Pripomenutie val: '.$reminder->pripomenutie_val.' Stav: '.$reminder->stav.' z IP: '.$ip_adresa.' v čase: '.$cas);
                return redirect()->route('reminders.index');
            }
        }

        return back()->withInput()->with('errors', 'Error creating new company');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Reminder  $reminder
     * @return \Illuminate\Http\Response
     */
    public function show(Reminder $reminder)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Reminder  $reminder
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $findreminder = Reminder::find($id);
        if((Auth::check())&&((Auth::user()->mod_7)==1)){

            return view('reminders.edit',['reminder'=>$findreminder]);
        }
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Reminder  $reminder
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Reminder $reminder)
    {
        if((Auth::check())&&((Auth::user()->mod_7)==1)){
            $updated = $reminder->update([
                'pripomienka' => $request->input('pripomienka'),
                'datum' => $request->input('terminpripomienky'),
                'opakovanie_val' => $request->input('opakovanie_val'),
                'opakovanie_num' => $request->input('opakovanie_num'),
                'pripomenutie_num' => $request->input('upozornenie_num'),
                'pripomenutie_val' => $request->input('upozornenie_val'),
                'stav' => $request->input('stavpripomienky'),
                'user_id' => Auth::id()
            ]);
            if (! $updated){
                return back()->withInput();
            }
            $ip_adresa = $request->getClientIp();
            $cas = Carbon::now()->toDateTimeString();
            Log::channel('reminders')->info('Použivateľ : '.Auth::user()->name.' ID: '.Auth::user()->id.' aktualizoval pripomienku s ID: '.$reminder->id.' Pripomienka: '.$reminder->pripomienka.' Dátum pripomienky: '.$reminder->datum.' Opakovanie val: '.$reminder->opakovanie_val.' Opakovanie num: '.$reminder->opakovanie_num.' Pripomenutie num: '.$reminder->pripomenutie_num.' Pripomenutie val: '.$reminder->pripomenutie_val.' Stav: '.$reminder->stav.' z IP: '.$ip_adresa.' v čase: '.$cas);

resources/views/reminders/all.blade.php
@extends('admin_template')

@section('content')
    <div class='row'>
        <div class='col-md-12'>
            <!-- Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Zoznam všetkých pripomienok</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body">

                    <div class="box">

                        <!-- /.box-header -->
                        <div class="box-body">

                            <table id="example1" class="table table-bordered table-striped">
                                <tr>
                                    <th>Por. číslo</th>
                                    <th>Pripomienka</th>
                                    <th>Dátum udalosti</th>
                                    <th>Opakovanie za</th>
                                    <th>Upozornenie pred</th>
                                    <th>Stav</th>
                                    <th>Dátum vytvorenia</th>
                                    <th>Editácia</th>


                                </tr>

                                @foreach ($reminders as $reminder)
                                       <tr>
                                            <td>{{$reminder->id}}</td>
                                            <td>{{$reminder->pripomienka}}</td>
                                           <td>{{($reminder->datum ? date('d.m.Y', strtotime($reminder->datum)): '')}}</td>
                                            <td>{{$reminder->opakovanie_num}}
                                                @switch($reminder->opakovanie_val)
                                                    @case(0)
                                                    Neopakuje sa
                                                    @break
                                                    @case(1)
                                                    dní
                                                    @break
                                                    @case(2)
                                                    týždne
                                                    @break
                                                    @case(3)
                                                    mesiace
                                                    @break
                                                    @case(4)
                                                    roky
                                                    @break
                                                    @default
                                                @endswitch
                                                </td>
                                            <td>{{$reminder->pripomenutie_num}}
                                                @switch($reminder->pripomenutie_val)
                                                    @case(1)
                                                    dní
                                                    @break
                                                    @case(2)
                                                    týždne
                                                    @break
                                                    @case(3)
                                                    mesiace
                                                    @break
                                                    @default
                                                @endswitch
                                            </td>
                                            <td>
                                                @switch($reminder->stav)
                                                    @case(0)
                                                    Neaktívna
                                                    @break
                                                    @case(1)
                                                    Aktívna
                                                    @break
                                                    @default
                                                @endswitch
                                            </td>
                                            <td>{{$reminder->created_at->format('d.m.Y')}}</td>
                                            <td><a href="/reminders/{{ $reminder->id }}/edit">Editovať</a></td>
                                        </tr>
                                @endforeach
                            </table>
                            {{ $reminders->links() }}

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div><!-- /.box-body -->

            </div><!-- /.box -->
        </div><!-- /.col -->



    </div><!-- /.row -->

@endsection

resources/views/reminders/create.blade.php
@extends('admin_template')
<head>
    <link href="/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap-datepicker.js"></script>

</head>

@section('content')
            <div class="row">

                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Vytvoriť pripomienku</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form  method="post" action="{{ route('reminders.store') }}" role="form">
                            {{ csrf_field() }}
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Zadajte pripomienku:</label>
                                    <input name="pripomienka" type="text" required class="form-control" id="exampleInputEmail1" placeholder="Zadajte pripomienku">
                                </div>
                                <div class="form-group">
                                    <label>Stav:</label>
                                    <select name="stavpripomienky" class="form-control">
                                        <option value="1">Aktívna</option>
                                        <option value="0">Neaktívna</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Dátum:</label>
                                    <div class='input-group date' id='datetimepicker1'>
                                        <input name="terminpripomienky" type='text'  class="form-control" />
                                        <span class="input-group-addon">
                                     <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Interval opakovania:</label>
                                    <input type="number" name="opakovanie_num" min="0" max="100" step="1" value="1" class="form-control">
                                    <select name="opakovanie_val" class="form-control">
                                        <option value="0">Neopakuje sa</option>
                                        <option value="1">Dní</option>
                                        <option value="2">Týždne</option>
                                        <option value="3">Mesiace</option>
                                        <option value="4">Roky</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Upozornenie pred udalosťou:</label>
                                    <input type="number" name="upozornenie_num" min="0" max="100" step="1" value="1" class="form-control">
                                    <select name="upozornenie_val" class="form-control">
                                        <option value="1">Dni</option>
                                        <option value="2">Týždne</option>
                                        <option value="3">Mesiace</option>
                                    </select>
                                </div>


                             </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.tab-pane -->
            </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>
            <script type="text/javascript">
                $('.date').datepicker({
                    //format: 'dd-mm-yyyy'
                    format: 'yyyy-mm-dd'
                });

            </script>


@endsection

resources/views/reminders/edit.blade.php
@extends('admin_template')
<head>
    <link href="/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap-datepicker.js"></script>

</head>

@section('content')
            <div class="row">

                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Vytvoriť pripomienku</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form  method="post" action="{{route('reminders.update',[$reminder->id])}}" role="form">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Zadajte pripomienku</label>
                                    <input name="pripomienka" type="text" value="{{$reminder->pripomienka}}" required class="form-control" id="exampleInputEmail1" placeholder="Zadajte pripomienku">
                                </div>
                                <div class="form-group">
                                    <label>Stav:</label>
                                    <select name="stavpripomienky" class="form-control">
                                        @if($reminder->stav == 1)
                                            <option value="1" selected>Aktívna</option>
                                            <option value="0">Neaktívna</option>
                                        @else
                                            <option value="1">Aktívna</option>
                                            <option value="0" selected>Neaktívna</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Dátum:</label>
                                    <div class='input-group date' id='datetimepicker1'>
                                        <input name="terminpripomienky" value="{{$reminder->datum}}" type='text'  class="form-control" />
                                        <span class="input-group-addon">
                                     <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Interval opakovania:</label>
                                    <input type="number" name="opakovanie_num" value="{{$reminder->opakovanie_num}}" min="0" max="100" step="1" value="1" class="form-control">
                                    <select name="opakovanie_val" class="form-control">
                                        @if($reminder->opakovanie_val == 0)
                                            <option value="0" selected>Neopakuje sa</option>
                                            <option value="1">Dní</option>
                                            <option value="2">Týždne</option>
                                            <option value="3">Mesiace</option>
                                            <option value="4">Roky</option>
                                        @elseif ($reminder->opakovanie_val == 1)
                                            <option value="0">Neopakuje sa</option>
                                            <option value="1" selected>Dní</option>
                                            <option value="2">Týždne</option>
                                            <option value="3">Mesiace</option>
                                            <option value="4">Roky</option>
                                        @elseif ($reminder->opakovanie_val == 2)
                                            <option value="0">Neopakuje sa</option>
                                            <option value="1">Dní</option>
                                            <option value="2" selected>Týždne</option>
                                            <option value="3">Mesiace</option>
                                            <option value="4">Roky</option>
                                        @elseif ($reminder->opakovanie_val == 3)
                                            <option value="0">Neopakuje sa</option>
                                            <option value="1">Dní</option>
                                            <option value="2">Týždne</option>
                                            <option value="3" selected>Mesiace</option>
                                            <option value="4">Roky</option>
                                        @else
                                            <option value="0">Neopakuje sa</option>
                                            <option value="1">Dní</option>
                                            <option value="2">Týždne</option>
                                            <option value="3">Mesiace</option>
                                            <option value="4" selected>Roky</option>
                                        @endif
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Upozornenie pred udalosťou:</label>
                                    <input type="number" name="upozornenie_num" value="{{$reminder->pripomenutie_num}}" min="0" max="100" step="1" value="1" class="form-control">
                                    <select name="upozornenie_val" class="form-control">
                                        @if($reminder->pripomenutie_val == 1)
                                            <option value="1" selected>Dní</option>
                                            <option value="2">Týždne</option>
                                            <option value="3">Mesiace</option>
                                        @elseif ($reminder->pripomenutie_val == 2)
                                            <option value="1">Dní</option>
                                            <option value="2" selected>Týždne</option>
                                            <option value="3">Mesiace</option>
                                        @else
                                            <option value="1">Dní</option>
                                            <option value="2">Týždne</option>
                                            <option value="3" selected>Mesiace</option>

                                        @endif
                                    </select>
                                </div>


                             </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.tab-pane -->
            </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>
            <script type="text/javascript">
                $('.date').datepicker({
                    //format: 'dd-mm-yyyy'
                    format: 'yyyy-mm-dd'
                });

            </script>


@endsection