routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');
Route::resource('/','ContractsController');
Route::resource('contracts','ContractsController');
Route::get('tasks/create/{contract_id?}', 'TasksController@create');
Route::resource('tasks', 'TasksController');
Route::resource('stock', 'StockController');
Route::resource('definedtasks', 'DefinedTasksController');
Route::resource('subdefinedtasks', 'SubdefinedTasksController');
Route::resource('employees', 'EmployeesController');
Route::resource('clients', 'ClientsController');
Route::resource('contracts_statuses', 'ContractsStatusController');
Route::resource('contracts_types', 'ContractsTypesController');
Route::resource('upload', 'DownloadFilesController');
Route::resource('statistics', 'StatisticsController');
Route::resource('statisticsclient', 'StatisticsClientController');
Route::resource('diary', 'DiaryController');
Route::resource('cash', 'CashController');
Route::get('/contracts/getPDF/{id}','ContractsController@generatePDF');
Route::resource('deadline', 'ContractsDeadlineesController');
Route::get('reminders/all', 'ReminderController@all');
Route::resource('reminders', 'ReminderController');
Route::resource('taskstatistics', 'TaskStatisticsController');
Route::resource('sendstock', 'SendStockController');
Route::resource('contractors', 'ContractorController');
Route::resource('status_invoice', 'StatusInvoiceController');
Route::resource('invoice_payment', 'InvoicePaymentMethodController');
Route::resource('invoice', 'InvoiceController');
Route::resource('invoice_detail', 'InvoiceDetailController');
Route::get('/invoice/getPDF/{id}','InvoiceController@generatePDF');
Route::get('/invoice/dodaci-list/{id}','InvoiceController@generatePDFdodaci');
// Route::get('/invoice/print/{id}','InvoiceController@print');
Route::resource('messages', 'MessageController');
Route::resource('price_offers', 'PriceOfferController');
Route::get('/price_offers/getPDF/{id}','PriceOfferController@generatePDF');
Route::resource('users', 'UserController');
Route::resource('statisticsinvoice', 'StatisticsInvoicesController');
Route::resource('priceoffer_detail', 'PriceOfferDetailController');
Route::resource('client_export', 'ClientExportController');

app/ContractsStatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ContractsStatus extends Model
{
    protected $fillable = [
        'id',
        'nazov_stavu',

    ];
    public function contract(){
        return $this->belongsTo('App\Contract');

    }
}

app/Http/Controllers/ContractsStatusController.php
<?php

namespace App\Http\Controllers;

use App\ContractsStatus;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Log;
use Carbon\Carbon;

class ContractsStatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        $contracts_statuses= ContractsStatus::all();
        return view('contractsstatus.index',['contracts_statuses'=>$contracts_statuses]);
        }
        return back();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        return view('contractsstatus.create');
        }
        return back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
            $contracts_status = ContractsStatus::create([
                'nazov_stavu' => $request->input('nazov_stavu'),


            ]);
            if($contracts_status){
                $ip_adresa = $request->getClientIp();
                $cas = Carbon::now()->toDateTimeString();
                Log::channel('contractstatus')->info('Používateľ : '.Auth::user()->name.' ID: '.Auth::user()->id.' vytvoril stav zakazky s ID: '.$contracts_status->id.' Názov stavu: '.$contracts_status->nazov_stavu.' z IP: '.$ip_adresa.' v čase: '.$cas);
                return redirect()->route('contracts_statuses.index');
            }
        }

        return back()->withInput()->with('errors', 'Error creating new company');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ContractsStatus  $contractsStatus
     * @return \Illuminate\Http\Response
     */
    public function show(ContractsStatus $contractsStatus)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ContractsStatus  $contractsStatus
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        $contracts_statuses = ContractsStatus::find($id);
        return view('contractsstatus.edit',['contracts_statuses'=>$contracts_statuses]);
        }
        return back();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ContractsStatus  $contractsStatus
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ContractsStatus $contractsStatus)
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        $updated = $contractsStatus->update([
            'nazov_stavu' => $request->input('nazov_stavu')
        ]);
        if (! $updated){
            return back()->withInput();
        }
            $ip_adresa = $request->getClientIp();
            $cas = Carbon::now()->toDateTimeString();
            Log::channel('contractstatus')->info('Použivateľ : '.Auth::user()->name.' ID: '.Auth::user()->id.' aktualizoval stav zakazky s ID: '.$contractsStatus->id.' Názov stavu: '.$contractsStatus->nazov_stavu.' z IP: '.$ip_adresa.' v čase: '.$cas);
        return redirect()->route('contracts_statuses.index')
            ->with('success','Defined task update successfully');
        }
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ContractsStatus  $contractsStatus
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if((Auth::check())&&((Auth::user()->mod_1)==1)){
        try {
            $findcontractsStatus = ContractsStatus::find($id);

            $findcontractsStatus ->delete();
            return redirect()->route('contracts_statuses.index');
        }
        catch (\Exception $e) {
            return $e->getMessage();
        }
        }
        return back();
    }
}

resources/views/contractsstatus/create.blade.php
@extends('admin_template')

@section('content')
            <div class="row">

                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Pridať stav zákazky</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form  method="post" action="{{ route('contracts_statuses.store') }}" role="form">
                            {{ csrf_field() }}
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Názov</label>
                                    <input name="nazov_stavu" type="text" required class="form-control" id="exampleInputEmail1" placeholder="Zadajte názov stavu zákazky">
                                </div>
                             </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.tab-pane -->
            </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>



@endsection

resources/views/contractsstatus/edit.blade.php
@extends('admin_template')

@section('content')
            <div class="row">

                <!--/.col (left) -->
                <!-- right column -->
                <div class="col-md-12">

                    <!-- general form elements disabled -->
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Upraviť stav zákazky</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form  method="post" action="{{route('contracts_statuses.update',[$contracts_statuses->id])}}" role="form">
                          {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Názov</label>
                                    <input name="nazov_stavu" value="{{$contracts_statuses->nazov_stavu}}" type="text" required class="form-control" id="exampleInputEmail1" placeholder="Zadajte názov stavu zákazky">
                                </div>
                             </div>
                            <!-- /.box-body -->

                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Uložiť</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- /.tab-pane -->
            </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
                 immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>


@endsection

resources/views/contractsstatus/index.blade.php
@extends('admin_template')

@section('content')
    <div class='row'>
        <div class='col-md-12'>
            <a href="/contracts_statuses/create" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Pridať stav zákazky</a>
            <!-- Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Stavy zákazky</h3>
                    <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                    </div>
                </div>

                <div class="box-body">
                    <div class="box">
                        <!-- /.box-header -->
                        <div class="box-body">

                            <table id="example1" class="table table-bordered table-striped">
                                <tr>
                                    <th>Poradové číslo</th>
                                    <th>Názov stavu zákazky</th>
                                    <th>Editácia</th>



                                </tr>
                                <div style="display: none;">
                                    {{ $i=1 }}
                                </div>

                                @foreach ($contracts_statuses as $contracts_status)
                                    <tr>
                                        <td>{{ $i++ }}</td>
                                        <td>{{ $contracts_status->nazov_stavu }}</td>
                                        <td><a href="/contracts_statuses/{{ $contracts_status->id }}/edit">Editovať</a></td>

                                    </tr>
                                @endforeach

                            </table>

                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->

                </div><!-- /.box-body -->

            </div><!-- /.box -->
        </div><!-- /.col -->



    </div><!-- /.row -->

@endsection